version: 3
output: prefixed

env:
  CLUSTER_NAME: greenstar
  DOMAIN: greenstar.test

dotenv:
  - .env

run: when_changed

includes:

  cluster:
    taskfile: build/Taskfile-cluster.yaml
  dev:
    taskfile: build/Taskfile-dev.yaml
  dns:
    taskfile: build/Taskfile-dns.yaml
  gcp:
    taskfile: build/Taskfile-gcp.yaml
  github:
    taskfile: build/Taskfile-github.yaml
  graphql:
    taskfile: build/Taskfile-graphql.yaml
  helm:
    taskfile: build/Taskfile-helm.yaml
  test:
    taskfile: build/Taskfile-test.yaml
  tls:
    taskfile: build/Taskfile-tls.yaml
