generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"

commonAnnotations:
  grafana_folder: "Kubernetes"

configMapGenerator:

#################################################
# Single ConfigMap containing all of them
#################################################
#- name: grafana-dashboards
#  files:
#    - dashboards/k8s-system-api-server.json
#    - dashboards/k8s-system-coredns.json
#    - dashboards/k8s-views-global.json
#    - dashboards/k8s-views-namespaces.json
#    - dashboards/k8s-views-nodes.json
#    - dashboards/k8s-views-pods.json

#################################################
# Views Dashboards
#################################################

- name: dashboards-k8s-views-global
  files: [ dashboards/k8s-views-global.json ]

- name: dashboards-k8s-views-namespaces
  files: [ dashboards/k8s-views-namespaces.json ]

- name: dashboards-k8s-views-nodes
  files: [ dashboards/k8s-views-nodes.json ]

- name: dashboards-k8s-views-pods
  files: [ dashboards/k8s-views-pods.json ]

#################################################
# System / Addons Dashboards
#################################################

- name: dashboards-k8s-system-api-server
  files: [ dashboards/k8s-system-api-server.json ]

- name: dashboards-k8s-system-coredns
  files: [ dashboards/k8s-system-coredns.json ]

- name: dashboards-greenstar
  files: [ dashboards/greenstar.json ]
