name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  build-images:
    name: Build ${{ matrix.image }} image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image: [ acme, frontend, ratesjob, server ]
      fail-fast: true
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Docker Builder
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: |
            type=registry,mode=max,ref=ghcr.io/${{ github.repository }}/${{ matrix.image }}-cache:${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.ref_name }}
            type=registry,mode=max,ref=ghcr.io/${{ github.repository }}/${{ matrix.image }}-cache:main
          cache-to: |
            type=registry,mode=max,ref=ghcr.io/${{ github.repository }}/${{ matrix.image }}-cache:${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.ref_name }}
          context: ${{ matrix.image }}
          build-args: |
            VERSION=0.0.0+${{ github.sha }}
            VITE_GRAPHQL_API_URL=https://api.greenstar.test/graphql
          target: ci
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.image }}:${{ github.sha }}

  build-helm-package:
    name: Build Helm chart
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.package.outputs.version }}
    env:
      VERSION: "0.0.0+${{ github.sha }}"
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Package Helm chart
        run: |
          yq -i ".acme.image.tag = \"${IMAGES_TAG}\"" deploy/chart/values.yaml
          yq -i ".frontend.image.tag = \"${IMAGES_TAG}\"" deploy/chart/values.yaml
          yq -i ".ratesjob.image.tag = \"${IMAGES_TAG}\"" deploy/chart/values.yaml
          yq -i ".server.image.tag = \"${IMAGES_TAG}\"" deploy/chart/values.yaml
          helm package ./deploy/chart --app-version "${VERSION}" --version "${VERSION}"
        env:
          IMAGES_TAG: ${{ github.sha }}

      - name: Push Helm Chart
        run: |
          helm push *.tgz oci://ghcr.io/${{ github.repository_owner }}
