name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  verify-generated-code:
    name: Verify ${{ matrix.module }} generated code
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        module: [ acme, frontend, ratesjob, server ]
      fail-fast: true
    permissions:
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: npm
          cache-dependency-path: ${{ matrix.module }}/package-lock.json

      - name: Node Dependencies
        run: npm ci
        working-directory: ${{ matrix.module }}

      - name: Generate
        run: task generate-graphql-${{ matrix.module }}

      - name: Verify
        run: git diff --compact-summary --exit-code
